
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
import Nav from '../../components/Nav'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Photowalk',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Nav />
      <AppRouterCacheProvider>{children}</AppRouterCacheProvider>
    </html>
  )
}
